name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --only hosting
